name: Run Playwright Tests and Publish Allure Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.49.0-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and Playwright browsers
        run: |
          mvn dependency:resolve
          mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install-deps"

      - name: Run tests
        run: mvn clean test

      - name: Generate Allure Report
        run: |
          mvn allure:report
          mvn allure:aggregate

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site/allure-maven-plugin

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

