name: Run Playwright Tests and Deploy Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build com Maven e executar testes
        run: mvn clean test io.qameta.allure:allure-maven:2.10.0:report

      - name: Copiar Allure Report para a pasta esperada pelo Pages
        run: |
          mkdir -p gh-pages
          cp -r target/allure-report/* gh-pages/

      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
