name: Run Tests and Deploy Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.49.0-noble

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build dependencies
        run: mvn dependency:build-classpath -Dmdep.outputFile=cp.txt

      - name: Install Playwright Browsers
        run: |
          mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"

      - name: Run tests
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Copy Allure Report to public folder
        run: |
          mkdir -p site
          cp -r target/site/allure-maven-plugin/* site/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4